
export const SET_TITLE = 'SET_TITLE';

export const SET_WIDGET = 'SET_WIDGET';

export const SET_RADIAL_WIDGET = 'SET_RADIAL_WIDGET';

export const SET_DELIVERY_WIDGET = 'SET_DELIVERY_WIDGET';

export const SET_AGENTRETURN_WIDGET = 'SET_AGENTRETURN_WIDGET';

export const SET_TASK_WIDGET = 'SET_TASK_WIDGET';

export const SET_NONVISIT_WIDGET = 'SET_NONVISIT_WIDGET';

export const SET_LOCAL = 'SET_LOCAL';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';

export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const REPORTGRID_SETTINGS = 'REPORTGRID_SETTINGS';

export const REPORTGRID_DATA = 'REPORTGRID_DATA';

export const NESTEDGRID_DATA = 'NESTEDGRID_DATA';

export const DRIVERSTATUS_DATA = "DRIVERSTATUS_DATA";

export const DRIVERSTATUSPOPUP_DATA = "DRIVERSTATUSPOPUP_DATA";

export const COUNTRY_DATA = 'COUNTRY_DATA';

export const DISTRIBUTION_DATA = 'DISTRIBUTION_DATA';

export const DRIVER_DATE = "DRIVER_DATE";

export const LAYOUT_DATA = "LAYOUT_DATA";

export const MENU_DATA = "MENU_DATA";

export const FILTER_PARAMS = "FILTER_PARAMS";

export const TASKS_DATA = "TASKS_DATA";

export const AGENTSLIST_DATA = "AGENTSLIST_DATA";

export const TASKSTYPES_DATA = "TASKSTYPES_DATA";

export const TASKSRESULT_DATA = "TASKSRESULT_DATA";     

export const DELETEDTASKS_DATA = "DELETEDTASKS_DATA";

export const MAPSTRUCK_DATA = "MAPSTRUCK_DATA";

export const MAPSVISIT_DATA = "MAPSVISIT_DATA";

export const MAPSROAD_DATA = "MAPSROAD_DATA";

export const ENDDAY_DATA = "ENDDAY_DATA";

export const ENDDAYDETAILS_DATA = "ENDDAYDETAILS_DATA";

export const COLLECTIONNOTES_DATA = "COLLECTIONNOTES_DATA";

export const AGENTSREPORT_DATA = "AGENTSREPORT_DATA";

export const AGENTSREPORTNT_DATA = "AGENTSREPORTNT_DATA";