//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.LayoutRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MobiPlusWebDiplomatEntities : DbContext
    {
        public MobiPlusWebDiplomatEntities()
            : base("name=MobiPlusWebDiplomatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<MPLayout_GetUsers_Result> MPLayout_GetUsers(Nullable<long> sessionUserID)
        {
            var sessionUserIDParameter = sessionUserID.HasValue ?
                new ObjectParameter("SessionUserID", sessionUserID) :
                new ObjectParameter("SessionUserID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MPLayout_GetUsers_Result>("MPLayout_GetUsers", sessionUserIDParameter);
        }
    
        public virtual ObjectResult<MPLayout_GetReportStyles_Result> MPLayout_GetReportStyles(Nullable<long> styleID, Nullable<long> versionID)
        {
            var styleIDParameter = styleID.HasValue ?
                new ObjectParameter("StyleID", styleID) :
                new ObjectParameter("StyleID", typeof(long));
    
            var versionIDParameter = versionID.HasValue ?
                new ObjectParameter("VersionID", versionID) :
                new ObjectParameter("VersionID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MPLayout_GetReportStyles_Result>("MPLayout_GetReportStyles", styleIDParameter, versionIDParameter);
        }
    
        public virtual ObjectResult<MPLayout_GetSalesOrganizations_Result> MPLayout_GetSalesOrganizations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MPLayout_GetSalesOrganizations_Result>("MPLayout_GetSalesOrganizations");
        }
    
        public virtual ObjectResult<Layout_Reports2Form_SelectAll_Result> Layout_Reports2Form_SelectAll(Nullable<long> iFormID, Nullable<long> iTabID, Nullable<long> iReportID)
        {
            var iFormIDParameter = iFormID.HasValue ?
                new ObjectParameter("iFormID", iFormID) :
                new ObjectParameter("iFormID", typeof(long));
    
            var iTabIDParameter = iTabID.HasValue ?
                new ObjectParameter("iTabID", iTabID) :
                new ObjectParameter("iTabID", typeof(long));
    
            var iReportIDParameter = iReportID.HasValue ?
                new ObjectParameter("iReportID", iReportID) :
                new ObjectParameter("iReportID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_Reports2Form_SelectAll_Result>("Layout_Reports2Form_SelectAll", iFormIDParameter, iTabIDParameter, iReportIDParameter);
        }
    
        public virtual ObjectResult<Layout_MenuItems_SelectByUser_Result> Layout_MenuItems_SelectByUser(Nullable<long> userID, Nullable<int> languageID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(long));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_MenuItems_SelectByUser_Result>("Layout_MenuItems_SelectByUser", userIDParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_TabsItems_SelectByUser_Result> Layout_TabsItems_SelectByUser(Nullable<long> formID, Nullable<int> tabID, Nullable<long> userID, Nullable<int> languageID)
        {
            var formIDParameter = formID.HasValue ?
                new ObjectParameter("FormID", formID) :
                new ObjectParameter("FormID", typeof(long));
    
            var tabIDParameter = tabID.HasValue ?
                new ObjectParameter("TabID", tabID) :
                new ObjectParameter("TabID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(long));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_TabsItems_SelectByUser_Result>("Layout_TabsItems_SelectByUser", formIDParameter, tabIDParameter, userIDParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_Filter_DistributionCenter_Result> Layout_Filter_DistributionCenter(Nullable<long> countryID, Nullable<int> userID, Nullable<int> languageID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_Filter_DistributionCenter_Result>("Layout_Filter_DistributionCenter", countryIDParameter, userIDParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_POD_Widget_Customers_Result> Layout_POD_Widget_Customers(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate, Nullable<int> languageID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_Widget_Customers_Result>("Layout_POD_Widget_Customers", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_POD_Widget_NotFullDelivery_Result> Layout_POD_Widget_NotFullDelivery(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate, Nullable<int> languageID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_Widget_NotFullDelivery_Result>("Layout_POD_Widget_NotFullDelivery", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_POD_Widget_Delivery_Result> Layout_POD_Widget_Delivery(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate, Nullable<int> languageID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_Widget_Delivery_Result>("Layout_POD_Widget_Delivery", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_POD_Widget_AgentReturn_Result> Layout_POD_Widget_AgentReturn(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate, Nullable<int> languageID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_Widget_AgentReturn_Result>("Layout_POD_Widget_AgentReturn", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_POD_Widget_Tasks_Result> Layout_POD_Widget_Tasks(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate, Nullable<int> languageID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_Widget_Tasks_Result>("Layout_POD_Widget_Tasks", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_POD_Filter_Country_Result> Layout_POD_Filter_Country(Nullable<long> sessionUserID, Nullable<int> languageID)
        {
            var sessionUserIDParameter = sessionUserID.HasValue ?
                new ObjectParameter("SessionUserID", sessionUserID) :
                new ObjectParameter("SessionUserID", typeof(long));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_Filter_Country_Result>("Layout_POD_Filter_Country", sessionUserIDParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_ConcentrationActivity_PopUp_Result> Layout_POD_WEB_ConcentrationActivity_PopUp(string countryID, string distrID, string agentId, string fromDate, string toDate, string cycle)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(string));
    
            var distrIDParameter = distrID != null ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(string));
    
            var agentIdParameter = agentId != null ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var cycleParameter = cycle != null ?
                new ObjectParameter("Cycle", cycle) :
                new ObjectParameter("Cycle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_ConcentrationActivity_PopUp_Result>("Layout_POD_WEB_ConcentrationActivity_PopUp", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter, cycleParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_ConcentrationActivity_Result> Layout_POD_WEB_ConcentrationActivity(string countryID, string distrID, string agentId, string fromDate, string toDate)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(string));
    
            var distrIDParameter = distrID != null ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(string));
    
            var agentIdParameter = agentId != null ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_ConcentrationActivity_Result>("Layout_POD_WEB_ConcentrationActivity", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_GetReportColsData_Result> Layout_GetReportColsData(Nullable<long> reportID, Nullable<int> languageID)
        {
            var reportIDParameter = reportID.HasValue ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(long));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_GetReportColsData_Result>("Layout_GetReportColsData", reportIDParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_POD_Widget_NotVisit_Result> Layout_POD_Widget_NotVisit(string countryID, string distrID, string agentId, string fromDate, string toDate, Nullable<int> languageID)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(string));
    
            var distrIDParameter = distrID != null ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(string));
    
            var agentIdParameter = agentId != null ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var languageIDParameter = languageID.HasValue ?
                new ObjectParameter("LanguageID", languageID) :
                new ObjectParameter("LanguageID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_Widget_NotVisit_Result>("Layout_POD_Widget_NotVisit", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter, languageIDParameter);
        }
    
        public virtual ObjectResult<Layout_POD_Filter_Driver_Result> Layout_POD_Filter_Driver(Nullable<long> countryID, Nullable<long> distrID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_Filter_Driver_Result>("Layout_POD_Filter_Driver", countryIDParameter, distrIDParameter);
        }
    
        public virtual ObjectResult<Layout_UserLogin_Result> Layout_UserLogin(string userName, string password, string userIP)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var userIPParameter = userIP != null ?
                new ObjectParameter("UserIP", userIP) :
                new ObjectParameter("UserIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_UserLogin_Result>("Layout_UserLogin", userNameParameter, passwordParameter, userIPParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_ConcentrationActivityAllCountries_Result> Layout_POD_WEB_ConcentrationActivityAllCountries(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_ConcentrationActivityAllCountries_Result>("Layout_POD_WEB_ConcentrationActivityAllCountries", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_DriverStatusAll_Result> Layout_POD_WEB_DriverStatusAll(string countryID, string distrID, string agentId, string fromDate, string toDate)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(string));
    
            var distrIDParameter = distrID != null ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(string));
    
            var agentIdParameter = agentId != null ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_DriverStatusAll_Result>("Layout_POD_WEB_DriverStatusAll", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_DriverStatus_PopUp_Result> Layout_POD_WEB_DriverStatus_PopUp(string countryID, string distrID, string driverID, string taskDate, string toDate)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(string));
    
            var distrIDParameter = distrID != null ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(string));
    
            var driverIDParameter = driverID != null ?
                new ObjectParameter("DriverID", driverID) :
                new ObjectParameter("DriverID", typeof(string));
    
            var taskDateParameter = taskDate != null ?
                new ObjectParameter("TaskDate", taskDate) :
                new ObjectParameter("TaskDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_DriverStatus_PopUp_Result>("Layout_POD_WEB_DriverStatus_PopUp", countryIDParameter, distrIDParameter, driverIDParameter, taskDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_GetAgentsL_Result> Layout_GetAgentsL(string countryID, string distrID)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(string));
    
            var distrIDParameter = distrID != null ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_GetAgentsL_Result>("Layout_GetAgentsL", countryIDParameter, distrIDParameter);
        }
    
        public virtual ObjectResult<Layout_GetDriverTasks_Result> Layout_GetDriverTasks(Nullable<long> countryID, Nullable<long> agentID, string date, string toDate)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("AgentID", agentID) :
                new ObjectParameter("AgentID", typeof(long));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_GetDriverTasks_Result>("Layout_GetDriverTasks", countryIDParameter, agentIDParameter, dateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_GetTaskTypes_Result> Layout_GetTaskTypes(Nullable<long> countryID)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_GetTaskTypes_Result>("Layout_GetTaskTypes", countryIDParameter);
        }
    
        public virtual ObjectResult<Layout_SaveTask_Result> Layout_SaveTask(Nullable<long> taskID, string agentId, string customerCode, string address, string city, string dateFrom, string dateTo, Nullable<int> taskTypeID, string task, Nullable<long> mobiUserID, Nullable<long> countryID)
        {
            var taskIDParameter = taskID.HasValue ?
                new ObjectParameter("TaskID", taskID) :
                new ObjectParameter("TaskID", typeof(long));
    
            var agentIdParameter = agentId != null ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(string));
    
            var customerCodeParameter = customerCode != null ?
                new ObjectParameter("CustomerCode", customerCode) :
                new ObjectParameter("CustomerCode", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var dateFromParameter = dateFrom != null ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(string));
    
            var dateToParameter = dateTo != null ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(string));
    
            var taskTypeIDParameter = taskTypeID.HasValue ?
                new ObjectParameter("TaskTypeID", taskTypeID) :
                new ObjectParameter("TaskTypeID", typeof(int));
    
            var taskParameter = task != null ?
                new ObjectParameter("Task", task) :
                new ObjectParameter("Task", typeof(string));
    
            var mobiUserIDParameter = mobiUserID.HasValue ?
                new ObjectParameter("MobiUserID", mobiUserID) :
                new ObjectParameter("MobiUserID", typeof(long));
    
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_SaveTask_Result>("Layout_SaveTask", taskIDParameter, agentIdParameter, customerCodeParameter, addressParameter, cityParameter, dateFromParameter, dateToParameter, taskTypeIDParameter, taskParameter, mobiUserIDParameter, countryIDParameter);
        }
    
        public virtual ObjectResult<Layout_TaskDelete_Result> Layout_TaskDelete(Nullable<long> taskID, Nullable<long> countryID, string agentId, string dateFrom)
        {
            var taskIDParameter = taskID.HasValue ?
                new ObjectParameter("TaskID", taskID) :
                new ObjectParameter("TaskID", typeof(long));
    
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var agentIdParameter = agentId != null ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(string));
    
            var dateFromParameter = dateFrom != null ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_TaskDelete_Result>("Layout_TaskDelete", taskIDParameter, countryIDParameter, agentIdParameter, dateFromParameter);
        }
    
        public virtual ObjectResult<Layout_CustomersCordSelect_Result> Layout_CustomersCordSelect(Nullable<long> agentID, string date, Nullable<long> countryID, Nullable<long> distrID, string toDate)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("AgentID", agentID) :
                new ObjectParameter("AgentID", typeof(long));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_CustomersCordSelect_Result>("Layout_CustomersCordSelect", agentIDParameter, dateParameter, countryIDParameter, distrIDParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_CustomersRoadCordSelect_Result> Layout_CustomersRoadCordSelect(Nullable<long> agentID, Nullable<long> date, Nullable<long> countryID, string toDate)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("AgentID", agentID) :
                new ObjectParameter("AgentID", typeof(long));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(long));
    
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_CustomersRoadCordSelect_Result>("Layout_CustomersRoadCordSelect", agentIDParameter, dateParameter, countryIDParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_EndDay_Select_Result> Layout_POD_WEB_EndDay_Select(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_EndDay_Select_Result>("Layout_POD_WEB_EndDay_Select", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_EndDayDetails_Select_Result> Layout_POD_WEB_EndDayDetails_Select(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_EndDayDetails_Select_Result>("Layout_POD_WEB_EndDayDetails_Select", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_GetDriverGPSLocation_Result> Layout_GetDriverGPSLocation(Nullable<long> agentID, string date, Nullable<long> countryID, string toDate)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("AgentID", agentID) :
                new ObjectParameter("AgentID", typeof(long));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_GetDriverGPSLocation_Result>("Layout_GetDriverGPSLocation", agentIDParameter, dateParameter, countryIDParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_NotesCollection_Result> Layout_POD_WEB_NotesCollection(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_NotesCollection_Result>("Layout_POD_WEB_NotesCollection", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_AgentsReport_Result> Layout_POD_WEB_AgentsReport(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_AgentsReport_Result>("Layout_POD_WEB_AgentsReport", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_AgentsReportNoTarget_Result> Layout_POD_WEB_AgentsReportNoTarget(Nullable<long> countryID, Nullable<long> distrID, Nullable<long> agentId, string fromDate, string toDate)
        {
            var countryIDParameter = countryID.HasValue ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(long));
    
            var distrIDParameter = distrID.HasValue ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(long));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(long));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_AgentsReportNoTarget_Result>("Layout_POD_WEB_AgentsReportNoTarget", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_AgentDailyActivity_Result> Layout_POD_WEB_AgentDailyActivity(string countryID, string distrID, string agentId, string fromDate, string toDate)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(string));
    
            var distrIDParameter = distrID != null ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(string));
    
            var agentIdParameter = agentId != null ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_AgentDailyActivity_Result>("Layout_POD_WEB_AgentDailyActivity", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Layout_POD_WEB_AgentDailyActivity_PopUp_Result> Layout_POD_WEB_AgentDailyActivity_PopUp(string countryID, string distrID, string agentId, string fromDate, string custId)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("CountryID", countryID) :
                new ObjectParameter("CountryID", typeof(string));
    
            var distrIDParameter = distrID != null ?
                new ObjectParameter("DistrID", distrID) :
                new ObjectParameter("DistrID", typeof(string));
    
            var agentIdParameter = agentId != null ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var custIdParameter = custId != null ?
                new ObjectParameter("CustId", custId) :
                new ObjectParameter("CustId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Layout_POD_WEB_AgentDailyActivity_PopUp_Result>("Layout_POD_WEB_AgentDailyActivity_PopUp", countryIDParameter, distrIDParameter, agentIdParameter, fromDateParameter, custIdParameter);
        }
    }
}
