var newopts = {inGraphDataShow: true,

       inGraphDataPaddingX: 7,
       inGraphDataPaddingY: 7,
        inGraphDataAlign : "center",
        inGraphDataVAlign : "top",
        inGraphDataRotate : 1,
        inGraphDataFontFamily: "'Arial'",
        inGraphDataFontSize: 10,
        inGraphDataFontStyle: "bold",
        inGraphDataFontColor: "black",
        scaleOverlay: false,
        scaleOverride: false,
        scaleSteps: null,
        scaleStepWidth: 20,
        scaleStartValue: null,
        // seting x axis value.
        yAxisLabel : "מכירות",
        yAxisFontFamily : "'Arial'",
        yAxisFontSize : 16,
        yAxisFontStyle : "normal",
        yAxisFontColor : "#666",
        xAxisLabel : "סוכן",
      xAxisFontFamily : "'Arial'",
        xAxisFontSize : 16,
        xAxisFontStyle : "normal",
        xAxisFontColor : "#666",
        // y axis value
        scaleLineColor: "rgba(0,0,0,.1)",
        scaleLineWidth: 1,
        scaleShowLabels: true,

        scaleFontFamily: "'Arial'",
        scaleFontSize: 12,
        scaleFontStyle: "normal",
        scaleFontColor: "#666",
        scaleShowGridLines: true,
        scaleXGridLinesStep : 1,
        scaleYGridLinesStep : 1,
        scaleGridLineColor: "rgba(0,0,0,.05)",
        scaleGridLineWidth: 1,
        showYAxisMin: true,      // Show the minimum value on Y axis (in original version, this minimum is not displayed - it can overlap the X labels)
        rotateLabels: "smart",   // smart <=> 0 degre if space enough; otherwise 45 degres if space enough otherwise90 degre; 
        // you can force an integer value between 0 and 180 degres
        logarithmic: false, // can be 'fuzzy',true and false ('fuzzy' => if the gap between min and maximum is big it's using a logarithmic y-Axis scale
        scaleTickSizeLeft: 5,
        scaleTickSizeRight: 5,
        scaleTickSizeBottom: 5,
        scaleTickSizeTop: 5,
        bezierCurve: true,
        pointDot: true,
        pointDotRadius: 4,
        pointDotStrokeWidth: 2,
        datasetStroke: true,
        datasetStrokeWidth: 2,
        datasetFill: true,
        animation: true,
        animationSteps: 60,
        animationEasing: "easeOutQuart",
        onAnimationComplete: null,/*
        inGraphDataShow: true,
        datasetFill: false,
        scaleLabel: "lbl",
        scaleTickSizeRight: 5,
        scaleTickSizeLeft: 5,
        scaleTickSizeBottom: 5,
        scaleTickSizeTop: 5,
        scaleFontSize: 16,
        canvasBorders: true,
        canvasBordersWidth: 3,
        canvasBordersColor: "black",
        graphTitle: "Graph Title",
        graphTitleFontFamily: "'Arial'",
        graphTitleFontSize: 24,
        graphTitleFontStyle: "bold",
        graphTitleFontColor: "#666",
        graphSubTitle: "Graph Sub Title",
        graphSubTitleFontFamily: "'Arial'",
        graphSubTitleFontSize: 18,
        graphSubTitleFontStyle: "normal",
        graphSubTitleFontColor: "#666",
        footNote: "Footnote for the graph",
        footNoteFontFamily: "'Arial'",
        footNoteFontSize: 8,
        footNoteFontStyle: "bold",
        footNoteFontColor: "#666",
        legend: true,
        legendFontFamily: "'Arial'",
        legendFontSize: 8,
        legendFontStyle: "normal",
        legendFontColor: "#666",
        legendBlockSize: 8,
        legendBorders: true,
        legendBordersWidth: 1,
        legendBordersColors: "#666",
        yAxisLeft: true,
        yAxisRight: false,
        xAxisBottom: true,
        xAxisTop: false,
        yAxisLabel: "Y Axis Label",
        yAxisFontFamily: "'Arial'",
        yAxisFontSize: 16,
        yAxisFontStyle: "normal",
        yAxisFontColor: "#666",
        xAxisLabel: "pX Axis Label",
        xAxisFontFamily: "'Arial'",
        xAxisFontSize: 8,
        xAxisFontStyle: "normal",
        xAxisFontColor: "#666",
        yAxisUnit: "Y Unit",
        yAxisUnitFontFamily: "'Arial'",
        yAxisUnitFontSize: 8,
        yAxisUnitFontStyle: "normal",
        yAxisUnitFontColor: "#666",
        annotateDisplay: true,
        spaceTop: 0,
        spaceBottom: 0,
        spaceLeft: 0,
        spaceRight: 0,
        logarithmic: false,
              showYAxisMin : true,
        rotateLabels: "smart",
        xAxisSpaceOver: 0,
        xAxisSpaceUnder: 0,
        xAxisLabelSpaceAfter: 0,
        xAxisLabelSpaceBefore: 0,
        legendBordersSpaceBefore: 0,
        legendBordersSpaceAfter: 0,
        footNoteSpaceBefore: 0,
        footNoteSpaceAfter: 0,
        startAngle: 0,
        dynamicDisplay: true*/
    }